### ISSUE TITLE
Fail2Ban: Have not found any log file for domino jail

### ISSUE THREAD

**Issue by CKMartens** [nashcom/domino-startscript#1]
Hello,

I tried to integrate the jail into fail2ban for our Domino server. However, an error occurs when starting:

`Jun 02 13:03:27 secgw1 systemd[1]: Starting Fail2Ban Service...
Jun 02 13:03:27 secgw1 systemd[1]: Started Fail2Ban Service.
Jun 02 13:03:27 secgw1 fail2ban-server[1801831]: 2022-06-02 13:03:27,691 fail2ban                [1801831]: ERROR   Failed during configuration: Have not found any log file for domino jail
Jun 02 13:03:27 secgw1 fail2ban-server[1801831]: 2022-06-02 13:03:27,691 fail2ban                [1801831]: ERROR   Async configuration of server failed
Jun 02 13:03:27 secgw1 systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/n/a
Jun 02 13:03:27 secgw1 systemd[1]: fail2ban.service: Failed with result 'exit-code'.
`
The log file is available:
![image](https://user-images.githubusercontent.com/19702758/171617039-93dc1e0a-56f9-48d2-b91a-8dc7b04ceb76.png)

Even assigning the calculation to 666 for the log file did not solve the problem.

What else can I do?

**Comment by Daniel-Nashed** [comment]
if the file is there, maybe this is a timing issue?
was this file there when you started the fail2ban service?
fail2ban really wants that file -- even empty.
If not the service fails to start, when the jail is configured.
Domino keeps the file on shutdown and replaces it at restart.

There is not much we can do on the Domino side. 
But it should work. Did you try to restart the service?

**Comment by CKMartens** [comment]
Hello,
sorry for the late reply.
Yes, the file is there, and further tests by my colleagues and I show it is a timing issue. How can we fix this? We have already checked some solutions given in the files without success

**Comment by Daniel-Nashed** [comment]
Which file are you using? The notes.log created by the start script?
That's the one used by default and it is recreated on startup. It is not removed on shutdown.
So it should be always there when fail2ban starts.. It's really hard to tell, what you are doing with the detail level you are providing.
There are no known timing issues with standard configurations.

**Comment by CKMartens** [comment]
Yes, we use the notes.log file. Here is an excerpt from the jail.local

```
[domino]
enabled  = true
filter   = domino
logpath  = /local/notesdata/notes.log
backend  = polling

#port    = 80,443
port     = 0:65535
findtime = 3600
bantime  = 3600
maxretry = 4
ignoreip = 127.0.0.1/8
```
and the filter.d/domino.conf

```
[INCLUDES]

# not required
# before = common.conf

[Definition]

failregex = ^.*? (http|smtp|ldap|imap|pop3): .*? \[<HOST>\] authentication failure using internet password\s*$

ignoreregex =

[Init]

# European Date 31.12.2019 22:11:01
datepattern = %%d.%%m.%%Y %%H:%%M:%%S
```

I reinstalled fail2ban, set up the jails again, and now "only" a warning comes up, but fail2ban starts. I don't understand why but just accept it.

So the issue can be closed for this strange bug.

Another question is how I can map this log entry in the failregex:

```
[003546:000013-00007F12A17E5700] 28.05.2022 00:47:03   TLS/SSL connection 1.2.3.4(43058) -> 111.222.333.444(443) failed with rejected SSLv3 connection
[003546:000013-00007F12A17E5700] 28.05.2022 00:47:05   TLS/SSL connection 1.2.3.4(44866) -> 111.222.333.444(443) failed with rejected SSLv3 connection
[003546:000013-00007F12A17E5700] 28.05.2022 00:47:06   TLS/SSL connection 1.2.3.4(45534) -> 111.222.333.444(443) failed with rejected SSLv2 record
[003546:000013-00007F12A17E5700] 28.05.2022 00:47:09   TLS/SSL connection 1.2.3.4(48400) -> 111.222.333.444(443) failed with rejected SSLv3 connection
[003546:000013-00007F12A17E5700] 28.05.2022 00:47:11   TLS/SSL connection 1.2.3.4(50332) -> 111.222.333.444(443) failed with rejected SSLv3 connection
[003546:000013-00007F12A17E5700] 28.05.2022 00:47:20   TLS/SSL connection 1.2.3.4(57820) -> 111.222.333.444(443) failed with no supported ciphers
[003546:000013-00007F12A17E5700] 28.05.2022 00:47:33   TLS/SSL connection 1.2.3.4(40082) -> 111.222.333.444(443) failed with rejected unknown record type
```

**Comment by Daniel-Nashed** [comment]
good that it worked. and it is still strange.
I can't give general support for fail2ban, I am sorry.

It would be a good idea to also check the invalid TLS/SSL connections. 
This would "just" need another regex. But I can't currently look into it from my side to add it to the filter.

There could be multiple regex lines for each filter:

https://www.fail2ban.org/wiki/index.php/MANUAL_0_8#Configuration

If you want to try on your own and report back.
Cloning the filter should not be straightforward .. 

-- Daniel

**Comment by Daniel-Nashed** [comment]
Oh .. you made me curious .. 

Can you try this filter? I used it with the fail2ban test and it looks good there.

```
failregex = ^.*? (http|smtp|ldap|imap|pop3): .*? \[<HOST>\] authentication failure using internet password.*?
            ^.*? TLS/SSL connection <HOST>.*? failed with rejected.*?
```

**Comment by CKMartens** [comment]
Oh man, thanks for the quick reply.

Yes, the filter looks good.

Many thanks

Greetings, Carsten

**Comment by Daniel-Nashed** [comment]
Should we add this to the default rule set?
Is this is what admins would expect by default?

If not I can still add the line in a comment.

"Fail" usually is connected to log-in attempts. But I generally like the idea to stop all activity that can be harmful at the first layer of defense.

**Comment by CKMartens** [comment]
I would include it as info in the readme file and ind filter.de/domino.conf.

Would be interesting for some I think.

**Comment by Daniel-Nashed** [comment]
I made it the default and added test cases.
This was a quick change, but should work. Can you verify it is all good and give feedback?

https://github.com/nashcom/domino-startscript/commit/8247fd895d52359c74b46171b434ca89c1398d6b

Thanks for your idea and feedback!

Daniel

**Comment by Daniel-Nashed** [comment]
problem solved. new feature implemented.

**Comment by Daniel-Nashed** [comment]
There is just one side effect I just thought about.
If you use a an external scanner to check your TLS configuration, this will probably not work any more.
A scan causes a lot of errors for ciphers, which are not configured.

But you can use a local script behind the firewall. 
Here is a project I can recommend:

https://github.com/drwetter/testssl.sh
