### ISSUE TITLE
Domino console closed with any command on Rocky Linux 9

### ISSUE THREAD

**Issue by jdeniau35** [nashcom/domino-startscript#4]
Start console: domino console (ou domino monitor)
Type any command, for instance help
result "Live Console closed"
in /var/log/secure:
Jul 28 15:42:57 angstroem su[50231]: pam_unix(su-l:session): session opened for user notes(uid=1002) by sshaccessAccount123(uid=0)
Jul 28 15:43:00 angstroem su[50231]: pam_unix(su-l:session): session closed for user notes

**Comment by Daniel-Nashed** [comment]
Just build a Rocky Linux 9 container and tested the start script. 
It works as expected for me. I don't see any Rocky Linux 9 specific issue.

And without more information about your environment, I can't help .. 
It's not a known issue.

**Comment by jdeniau35** [comment]
Ok Daniel 
I’ll check what changed from Rocky linux 8.5 to 9 for pam or something else

**Comment by Daniel-Nashed** [comment]
Probably it is not a Rocky Linux problem. I did not test natively. So a container might be a bit different.
I would search in another direction. But I can't help you if you don't have any more details about your configuration etc.

**Comment by jdeniau35** [comment]
Sure I’ll give you all details asap. I’ve migrated from rl85 to rl9 in site (upgrade on same machine). Domino was Danube ep3 since the beginning. I’ll try to give all info.

**Comment by jdeniau35** [comment]
Solved: script was 330, I forced complète reinstall of 3.7 build, problem solved!
