### ISSUE TITLE
A question about LD_LIBRARY_PATH and Sametime

### ISSUE THREAD

**Issue by stasjok** [nashcom/domino-startscript#9]
In a recent commit d773105ab8743b8ccc2005530570930c0afc6714 `$Notes_ExecDirectory/STOpenSSL:$Notes_ExecDirectory/sticc` were removed from `LD_LIBRARY_PATH`. AFAIK it was added for Sametime support: https://blog.nashcom.de/nashcomblog.nsf/dx/domino-start-script-sametime-11-support.htm. Is it not needed anymore? Will feature version of startscript work with Sametime?

**Comment by Daniel-Nashed** [comment]
I removed it because I thought most environments did move to the newer Sametime offerings and no new ST servers are installed with the older software versions.

Do you think this is still really needed by customers? I don't see many customer on Linux having this need and if they are not upgrading their servers, they probably will also not update their start script...

**Comment by stasjok** [comment]
If those library paths are not needed anymore in newer Sametime versions, than OK. We have them in the `ststart` script and those paths are valid, so I presume they are still needed for our version. I just in progress to migrating to your domino startscript. Anyway I can add it to `DOMINO_ENV_FILE`. I was only mean to ask if it was a mistake removing it.

**Comment by Daniel-Nashed** [comment]
Newer ST versions are not based on Domino any more. So the support for ST on the Domino Linux side is not needed for newer versions.

But the path is still needed for the ST versions, which run on Domino.
I would highly recommend you move to a more current ST version. But if you stay on your current version you will continue to need the path.

ST and Domino on Linux don't have a good track record. Getting ST into a container was a good move for the product and I would like encourage your to look at the newer versions.

**Comment by stasjok** [comment]
Thank you very much for the explanation. I'm sorry for taking your time.

**Comment by Daniel-Nashed** [comment]
you are welcome! if it turns out you continue to need it we could add it again.
just reopen the issue if needed.

**Comment by stasjok** [comment]
> if it turns out you continue to need it we could add it again.

I will need it for some time. But I can add LD_LIBRARY_PATH to my config and the start script will prepend Notes_ExecDirectory directory to it. I just need to remember it if I would update the script (I'm on 3.8.0), because it looks like an backward incompatible change.
